export enum Events {
  IBD = "IBD",
  IBD_REQUEST = "IBD_REQUEST",
  IBD_RESPONSE = "IBD_RESPONSE",
  TXN_BROADCAST = "TXN_BROADCAST",
  TXN_VALIDATION = "TXN_VALIDATION",
  NEW_TRANSACTION = "NEW_TRANSACTION",
  NEW_BLOCK = "NEW_BLOCK",
  SELECTED_PROPOSER = "SELECTED_PROPOSER",
}
